version: '3'

# This makes EVERY task run inside the uv venv — no more missing packages
env_vars:
  VIRTUAL_ENV: .venv
  PATH: "{{.TaskfileDir}}/.venv/bin:{{.Env.PATH}}"

tasks:
  install:
    desc: Install all deps (run once or after changes)
    cmds:
      - uv sync
      - uv pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision torchaudio
      - uv pip install sentence-transformers faiss-cpu pyyaml rich numpy==1.26.4

  ingest:
    desc: Run social media ingestion
    cmds:
      - uv run python -m data.ingestion.run

  silver:
    desc: Enhanced silver layer with FAANG-level transformations
    cmds:
      - uv run python data/silver/process_enhanced.py

  generate:
    desc: Generate AI tweets from real data
    cmds:
      - uv run python data/marketing/generate.py --company {{.COMPANY}} --query "{{.QUERY}}"

  up:
    desc: Start all services
    cmds:
      - docker compose -f dev/docker-compose.yaml up -d --build

  down:
    desc: Stop services
    cmds:
      - docker compose -f dev/docker-compose.yaml down

  status:
    desc: Show status
    cmds:
      - docker compose -f dev/docker-compose.yaml ps
